on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n KubernetesDKRTest -g KubernetesDKRTestbf30-rg --location "South India" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n KubernetesDKRTest --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n KubernetesDKRTest --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n KubernetesDKRTest --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: kubernetesdkrtest.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/Application" -f  "Application/Dockerfile" -t kubernetesdkrtest.azurecr.io/jysinakscluster:${{ github.sha }}
        docker push kubernetesdkrtest.azurecr.io/jysinakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_jysinakscluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep jysinakscluster85c6 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace jysinakscluster85c6`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: jysinakscluster85c6
        container-registry-url: kubernetesdkrtest.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: jysinaksclusdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: jysinakscluster85c6
        manifests: |
          manifests/deployment-8.yml
          manifests/service-8.yml
        images: |
          kubernetesdkrtest.azurecr.io/jysinakscluster:${{ github.sha }}
        imagepullsecrets: |
          jysinaksclusdockerauth